log:
  filePath: "./log/tickmaker.log"

listener:
  port: 5432

client:
  host: "127.0.0.1"
  port: 6543

cp:
  prices:
    - symbol: "USD/JPY"
      code: 1
      base_tick: 136.54
      spread: 0.02
      sigma: 0.4
      r: 0.01
    - symbol: "EUR/JPY"
      code: 2
      base_tick: 144.870
      spread: 0.02
      sigma: 0.4
      r: 0.01
    - symbol: "GBP/JPY"
      code: 3
      base_tick: 163.4
      spread: 0.02
      sigma: 0.4
      r: 0.01
    - symbol: "AUD/JPY"
      code: 4
      base_tick: 92.09
      spread: 0.02
      sigma: 0.4
      r: 0.01
      

