-- 顧客
CREATE SEQUENCE CUSTOMER_ID_SEQ START 1;
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INTEGER DEFAULT NEXTVAL('CUSTOMER_ID_SEQ') PRIMARY KEY NOT NULL,
	NAME CHAR(32) NOT NULL,
	MAIL CHAR(32) UNIQUE NOT NULL,
	PASSWORD CHAR(64) NOT NULL,
	CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	UPDATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE CUSTOMER IS '顧客';

-- システム管理者
CREATE TABLE ADMIN_USER (
    ADMIN_USER_ID CHAR(32) PRIMARY KEY NOT NULL,
	NAME CHAR(32) NOT NULL,
	PASSWORD CHAR(64) NOT NULL,
	CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	UPDATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE ADMIN_USER IS 'システム管理者';

-- 注文
CREATE TABLE CUSTOMER_ORDER (
	CUSTOMER_ID INTEGER NOT NULL,
	ORDER_ID CHAR(32) PRIMARY KEY NOT NULL,
	ORDER_TYPE INTEGER NOT NULL,
	BUSINESS_DATE INTEGER NOT NULL,
	ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CUSTOMER_ORDER_INDEX1 ON CUSTOMER_ORDER (CUSTOMER_ID);
CREATE INDEX CUSTOMER_ORDER_INDEX3 ON CUSTOMER_ORDER (BUSINESS_DATE);
COMMENT ON TABLE CUSTOMER_ORDER IS '注文';
COMMENT ON COLUMN CUSTOMER_ORDER.ORDER_TYPE IS '注文種別 1: Speed, 1: 成行, 2: 指値, 3: 逆指値, 4: IFD, 5: OCO, 6: IFD-OCO, 7: 建玉整理, 8: 全決済';
COMMENT ON COLUMN CUSTOMER_ORDER.BUSINESS_DATE IS '営業日(YYYYMMDD)';

-- 注文ステータス
CREATE TABLE CUSTOMER_ORDER_STATUS (
	ORDER_ID CHAR(32) UNIQUE NOT NULL,
	ORDER_STATUS INTEGER NOT NULL,
	IS_END BOOLEAN NOT NULL,
	CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	UPDATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CUSTOMER_ORDER_STATUS_INDEX1 ON CUSTOMER_ORDER_STATUS (ORDER_ID);
CREATE INDEX CUSTOMER_ORDER_STATUS_INDEX2 ON CUSTOMER_ORDER_STATUS (IS_END);
COMMENT ON TABLE CUSTOMER_ORDER_STATUS IS '注文ステータス';
COMMENT ON COLUMN CUSTOMER_ORDER_STATUS.ORDER_ID IS '注文ID';
COMMENT ON COLUMN CUSTOMER_ORDER_STATUS.ORDER_STATUS IS '1: 新規, 2: 進行中, 3: 終了, 4: キャンセル';
COMMENT ON COLUMN CUSTOMER_ORDER_STATUS.IS_END IS '終了フラグ';

-- スピード注文
CREATE TABLE CUSTOMER_SPEED_ORDER (
	ORDER_ID CHAR(32) UNIQUE NOT NULL,
	IS_STRADDING BOOLEAN NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	ORDER_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL
);
CREATE INDEX CUSTOMER_SPEED_ORDER_INDEX1 ON CUSTOMER_SPEED_ORDER (ORDER_ID);
COMMENT ON TABLE CUSTOMER_SPEED_ORDER IS 'スピード注文';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.ORDER_ID IS '両建てフラグ';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.IS_STRADDING IS '両建てフラグ';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.SIDE IS '1: 買, 2: 売';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.ORDER_PRICE IS '注文時プライス';
COMMENT ON COLUMN CUSTOMER_SPEED_ORDER.QUANTITY IS '数量';

-- 成行注文
CREATE TABLE CUSTOMER_MARKET_ORDER (
	ORDER_ID CHAR(32) NOT NULL,
	OPEN_POSITION_ID INTEGER,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	ORDER_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL
);
CREATE INDEX CUSTOMER_MARKET_ORDER_INDEX1 ON CUSTOMER_MARKET_ORDER (ORDER_ID);
CREATE INDEX CUSTOMER_MARKET_ORDER_INDEX2 ON CUSTOMER_MARKET_ORDER (OPEN_POSITION_ID);
COMMENT ON TABLE CUSTOMER_MARKET_ORDER IS '成行注文';
COMMENT ON COLUMN CUSTOMER_MARKET_ORDER.ORDER_ID IS '注文ID';
COMMENT ON COLUMN CUSTOMER_MARKET_ORDER.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN CUSTOMER_MARKET_ORDER.SIDE IS '1: 買, 2: 売';
COMMENT ON COLUMN CUSTOMER_MARKET_ORDER.ORDER_PRICE IS '注文時プライス';
COMMENT ON COLUMN CUSTOMER_MARKET_ORDER.QUANTITY IS '数量';

-- 取引所注文
CREATE TABLE EXCHANGE_ORDER (
	EXCHANGE_ORDER_ID CHAR(32) PRIMARY KEY NOT NULL,
	ORDER_ID CHAR(32) NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	ORDER_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL,
	BUSINESS_DATE INTEGER NOT NULL,
	ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	EXECUTION_ID CHAR(32) NOT NULL,
	EXECUTION_PRICE DECIMAL(20,10) NOT NULL,
	EXCHANGE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX EXCHANGE_ORDER_INDEX1 ON EXCHANGE_ORDER (ORDER_ID);
COMMENT ON TABLE EXCHANGE_ORDER IS '取引所注文';
COMMENT ON COLUMN EXCHANGE_ORDER.EXCHANGE_ORDER_ID IS '取引所注文ID';
COMMENT ON COLUMN EXCHANGE_ORDER.ORDER_ID IS '注文ID';
COMMENT ON COLUMN EXCHANGE_ORDER.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN EXCHANGE_ORDER.SIDE IS '1: 買, 2: 売';
COMMENT ON COLUMN EXCHANGE_ORDER.ORDER_PRICE IS '注文時プライス';
COMMENT ON COLUMN EXCHANGE_ORDER.QUANTITY IS '数量';
COMMENT ON COLUMN EXCHANGE_ORDER.ORDER_DATE IS '注文日時';
COMMENT ON COLUMN EXCHANGE_ORDER.EXECUTION_ID IS '取引所注文応答ID';
COMMENT ON COLUMN EXCHANGE_ORDER.EXECUTION_PRICE IS '約定時プライス';
COMMENT ON COLUMN EXCHANGE_ORDER.EXCHANGE_DATE IS '約定日時';

-- 取引所注文ステータス
CREATE TABLE EXCHANGE_ORDER_STATUS (
	EXCHANGE_ORDER_ID CHAR(32) UNIQUE NOT NULL,
	EXCHANGE_ORDER_STATUS INTEGER NOT NULL,
	IS_END BOOLEAN NOT NULL
);
CREATE INDEX EXCHANGE_ORDER_STATUS_INDEX1 ON EXCHANGE_ORDER_STATUS (IS_END);
COMMENT ON TABLE EXCHANGE_ORDER_STATUS IS '取引所注文ステータス';
COMMENT ON COLUMN EXCHANGE_ORDER_STATUS.EXCHANGE_ORDER_ID IS '取引所注文ID';
COMMENT ON COLUMN EXCHANGE_ORDER_STATUS.EXCHANGE_ORDER_STATUS IS '0: 新規, 1: 約定, 2: リジェクト';
COMMENT ON COLUMN EXCHANGE_ORDER_STATUS.IS_END IS '終了フラグ';


-- 顧客取引
CREATE TABLE CUSTOMER_DEAL (
	CUSTOMER_ID INTEGER NOT NULL,
	CUSTOMER_DEAL_ID CHAR(32) UNIQUE NOT NULL,
	SETTLE_TYPE INTEGER NOT NULL,
	IS_STRADDING BOOLEAN NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	OPEN_SIDE INTEGER NOT NULL,
	OPEN_PRICE DECIMAL(20,10) NOT NULL,
	FILL_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL,
	PROFIT_LOSS DECIMAL(20,10) NOT NULL,
	BUSINESS_DATE INTEGER NOT NULL,
	ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CUSTOMER_DEAL_INDEX1 ON CUSTOMER_DEAL (CUSTOMER_ID);
CREATE INDEX CUSTOMER_DEAL_INDEX2 ON CUSTOMER_DEAL (BUSINESS_DATE);
COMMENT ON TABLE CUSTOMER_DEAL IS '顧客取引';
COMMENT ON COLUMN CUSTOMER_DEAL.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN CUSTOMER_DEAL.CUSTOMER_DEAL_ID IS '顧客取引ID';
COMMENT ON COLUMN CUSTOMER_DEAL.SETTLE_TYPE IS '決済種別 1: 新規, 2: 決済';
COMMENT ON COLUMN CUSTOMER_DEAL.IS_STRADDING IS '建玉整理フラグ';
COMMENT ON COLUMN CUSTOMER_DEAL.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN CUSTOMER_DEAL.OPEN_SIDE IS '新規注文時サイド 1: 買, 2: 売';
COMMENT ON COLUMN CUSTOMER_DEAL.OPEN_PRICE IS '新規注文時プライス';
COMMENT ON COLUMN CUSTOMER_DEAL.FILL_PRICE IS '決済時プライス';
COMMENT ON COLUMN CUSTOMER_DEAL.QUANTITY IS '数量';
COMMENT ON COLUMN CUSTOMER_DEAL.PROFIT_LOSS IS '収益';
COMMENT ON COLUMN CUSTOMER_DEAL.BUSINESS_DATE IS '営業日(YYYYMMDD)';

-- 顧客ポジション
CREATE SEQUENCE OPEN_POSITION_ID_SEQ START 1;
CREATE TABLE CUSTOMER_OPEN_POSITION (
	CUSTOMER_ID INTEGER NOT NULL,
	OPEN_POSITION_ID INTEGER DEFAULT NEXTVAL('OPEN_POSITION_ID_SEQ') PRIMARY KEY NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	OPEN_PRICE DECIMAL(20,10) NOT NULL,
	LAST_QUANTITY DECIMAL(20) NOT NULL,
	IS_END BOOLEAN NOT NULL
);
CREATE INDEX CUSTOMER_OPEN_POSITION_INDEX1 ON CUSTOMER_OPEN_POSITION (CUSTOMER_ID);
CREATE INDEX CUSTOMER_OPEN_POSITION_INDEX2 ON CUSTOMER_OPEN_POSITION (IS_END);
COMMENT ON TABLE CUSTOMER_OPEN_POSITION IS '顧客ポジション';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.OPEN_POSITION_ID IS '顧客ポジションID';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.SIDE IS 'サイド 1: 買, 2: 売';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.OPEN_PRICE IS '新規注文時プライス';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.LAST_QUANTITY IS '残数量';
COMMENT ON COLUMN CUSTOMER_OPEN_POSITION.IS_END IS '終了フラグ';