-- 顧客注文
CREATE TABLE CUSTOMER_ORDER (
	ORDER_ID CHAR(32) PRIMARY KEY NOT NULL,
	CUSTOMER_ORDER_ID CHAR(32) NOT NULL,
	ORDER_RESULT INTEGER NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	ORDER_PRICE DECIMAL(20,10) NOT NULL,
	EXECUTION_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL,
	BUSINESS_DATE INTEGER NOT NULL,
	ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE CUSTOMER_ORDER IS '顧客注文';
COMMENT ON COLUMN CUSTOMER_ORDER.ORDER_ID IS '注文ID';
COMMENT ON COLUMN CUSTOMER_ORDER.CUSTOMER_ORDER_ID IS '顧客注文ID';
COMMENT ON COLUMN CUSTOMER_ORDER.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN CUSTOMER_ORDER.SIDE IS '1: 買, 2: 売';
COMMENT ON COLUMN CUSTOMER_ORDER.ORDER_PRICE IS '注文時プライス';
COMMENT ON COLUMN CUSTOMER_ORDER.EXECUTION_PRICE IS '約定時プライス';
COMMENT ON COLUMN CUSTOMER_ORDER.QUANTITY IS '数量';
COMMENT ON COLUMN CUSTOMER_ORDER.BUSINESS_DATE IS '営業日(YYYYMMDD)';
COMMENT ON COLUMN CUSTOMER_ORDER.ORDER_DATE IS '注文日時';

-- 取引
CREATE TABLE DEALING (
	DEALING_ID CHAR(32) PRIMARY KEY NOT NULL,
	ORDER_ID CHAR(32) NOT NULL,
	SETTLE_TYPE INTEGER NOT NULL,
	DEAL_TYPE BOOLEAN NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	OPEN_SIDE INTEGER NOT NULL,
	OPEN_PRICE DECIMAL(20,10) NOT NULL,
	FILL_PRICE DECIMAL(20,10) NOT NULL,
	QUANTITY DECIMAL(20) NOT NULL,
	PROFIT_LOSS DECIMAL(20,10) NOT NULL,
	BUSINESS_DATE INTEGER NOT NULL,
	ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX DEALING_INDEX1 ON DEALING (ORDER_ID);
CREATE INDEX DEALING_INDEX2 ON DEALING (BUSINESS_DATE);
COMMENT ON TABLE DEALING IS '取引';
COMMENT ON COLUMN DEALING.DEALING_ID IS '取引ID';
COMMENT ON COLUMN DEALING.ORDER_ID IS '注文ID';
COMMENT ON COLUMN DEALING.SETTLE_TYPE IS '決済種別 1: 新規, 2: 決済';
COMMENT ON COLUMN DEALING.DEAL_TYPE IS '取引種別: 1: 顧客注文, 2: カバー注文, 3: 建玉整理';
COMMENT ON COLUMN DEALING.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN DEALING.OPEN_SIDE IS '新規注文時サイド 1: 買, 2: 売';
COMMENT ON COLUMN DEALING.OPEN_PRICE IS '新規注文時プライス';
COMMENT ON COLUMN DEALING.FILL_PRICE IS '決済時プライス';
COMMENT ON COLUMN DEALING.QUANTITY IS '数量';
COMMENT ON COLUMN DEALING.PROFIT_LOSS IS '収益';
COMMENT ON COLUMN DEALING.BUSINESS_DATE IS '営業日(YYYYMMDD)';
COMMENT ON COLUMN DEALING.ORDER_DATE IS '注文日時';

-- 有効ポジション
CREATE SEQUENCE OPEN_POSITION_ID_SEQ START 1;
CREATE TABLE OPEN_POSITION (
	OPEN_POSITION_ID INTEGER DEFAULT NEXTVAL('OPEN_POSITION_ID_SEQ') PRIMARY KEY NOT NULL,
	COMMODITY_CODE INTEGER NOT NULL,
	SIDE INTEGER NOT NULL,
	OPEN_PRICE DECIMAL(20,10) NOT NULL,
	LAST_QUANTITY DECIMAL(20) NOT NULL,
	IS_END BOOLEAN NOT NULL
);
CREATE INDEX OPEN_POSITION_INDEX1 ON OPEN_POSITION (IS_END);
CREATE INDEX OPEN_POSITION_INDEX2 ON OPEN_POSITION (OPEN_PRICE);
COMMENT ON TABLE OPEN_POSITION IS '有効ポジション';
COMMENT ON COLUMN OPEN_POSITION.OPEN_POSITION_ID IS 'ポジションID';
COMMENT ON COLUMN OPEN_POSITION.COMMODITY_CODE IS '銘柄コード';
COMMENT ON COLUMN OPEN_POSITION.SIDE IS 'サイド 1: 買, 2: 売';
COMMENT ON COLUMN OPEN_POSITION.OPEN_PRICE IS 'プライス';
COMMENT ON COLUMN OPEN_POSITION.LAST_QUANTITY IS '残数量';
COMMENT ON COLUMN OPEN_POSITION.IS_END IS '終了フラグ';